# Generated by Django 5.1.4 on 2025-03-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='mumbai', max_length=255),
            preserve_default=False,
        ),
    ]
