# Generated by Django 5.1.4 on 2025-03-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_booking_additional_requests_booking_guest_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.CharField(default='mumbai', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('CULTURAL', 'Cultural'), ('CORPORATE', 'Corporate/Business'), ('SPORTS', 'Sports'), ('SOCIAL', 'Social'), ('EDUCATIONAL', 'Educational'), ('CHARITY', 'Charity/Fundraising')], max_length=20),
        ),
    ]
