# Generated by Django 5.1.6 on 2025-03-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_booking',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
